// +build !tcell

// Auto-generated by internal/cmd/gensym/gensym.go. DO NOT EDIT!
package peco

import (
	"github.com/nsf/termbox-go"
)

type KeyCode = termbox.Key

const (
	KeyF1             KeyCode = termbox.KeyF1
	KeyF2             KeyCode = termbox.KeyF2
	KeyF3             KeyCode = termbox.KeyF3
	KeyF4             KeyCode = termbox.KeyF4
	KeyF5             KeyCode = termbox.KeyF5
	KeyF6             KeyCode = termbox.KeyF6
	KeyF7             KeyCode = termbox.KeyF7
	KeyF8             KeyCode = termbox.KeyF8
	KeyF9             KeyCode = termbox.KeyF9
	KeyF10            KeyCode = termbox.KeyF10
	KeyF11            KeyCode = termbox.KeyF11
	KeyF12            KeyCode = termbox.KeyF12
	KeyInsert         KeyCode = termbox.KeyInsert
	KeyDelete         KeyCode = termbox.KeyDelete
	KeyHome           KeyCode = termbox.KeyHome
	KeyEnd            KeyCode = termbox.KeyEnd
	KeyPgup           KeyCode = termbox.KeyPgup
	KeyPgdn           KeyCode = termbox.KeyPgdn
	KeyArrowUp        KeyCode = termbox.KeyArrowUp
	KeyArrowDown      KeyCode = termbox.KeyArrowDown
	KeyArrowLeft      KeyCode = termbox.KeyArrowLeft
	KeyArrowRight     KeyCode = termbox.KeyArrowRight
	MouseLeft         KeyCode = termbox.MouseLeft
	MouseMiddle       KeyCode = termbox.MouseMiddle
	MouseRight        KeyCode = termbox.MouseRight
	MouseRelease      KeyCode = termbox.MouseRelease
	MouseWheelUp      KeyCode = termbox.MouseWheelUp
	MouseWheelDown    KeyCode = termbox.MouseWheelDown
	KeyCtrlTilde      KeyCode = termbox.KeyCtrlTilde
	KeyCtrl2          KeyCode = termbox.KeyCtrl2
	KeyCtrlSpace      KeyCode = termbox.KeyCtrlSpace
	KeyCtrlA          KeyCode = termbox.KeyCtrlA
	KeyCtrlB          KeyCode = termbox.KeyCtrlB
	KeyCtrlC          KeyCode = termbox.KeyCtrlC
	KeyCtrlD          KeyCode = termbox.KeyCtrlD
	KeyCtrlE          KeyCode = termbox.KeyCtrlE
	KeyCtrlF          KeyCode = termbox.KeyCtrlF
	KeyCtrlG          KeyCode = termbox.KeyCtrlG
	KeyBackspace      KeyCode = termbox.KeyBackspace
	KeyCtrlH          KeyCode = termbox.KeyCtrlH
	KeyTab            KeyCode = termbox.KeyTab
	KeyCtrlI          KeyCode = termbox.KeyCtrlI
	KeyCtrlJ          KeyCode = termbox.KeyCtrlJ
	KeyCtrlK          KeyCode = termbox.KeyCtrlK
	KeyCtrlL          KeyCode = termbox.KeyCtrlL
	KeyEnter          KeyCode = termbox.KeyEnter
	KeyCtrlM          KeyCode = termbox.KeyCtrlM
	KeyCtrlN          KeyCode = termbox.KeyCtrlN
	KeyCtrlO          KeyCode = termbox.KeyCtrlO
	KeyCtrlP          KeyCode = termbox.KeyCtrlP
	KeyCtrlQ          KeyCode = termbox.KeyCtrlQ
	KeyCtrlR          KeyCode = termbox.KeyCtrlR
	KeyCtrlS          KeyCode = termbox.KeyCtrlS
	KeyCtrlT          KeyCode = termbox.KeyCtrlT
	KeyCtrlU          KeyCode = termbox.KeyCtrlU
	KeyCtrlV          KeyCode = termbox.KeyCtrlV
	KeyCtrlW          KeyCode = termbox.KeyCtrlW
	KeyCtrlX          KeyCode = termbox.KeyCtrlX
	KeyCtrlY          KeyCode = termbox.KeyCtrlY
	KeyCtrlZ          KeyCode = termbox.KeyCtrlZ
	KeyEsc            KeyCode = termbox.KeyEsc
	KeyCtrlLsqBracket KeyCode = termbox.KeyCtrlLsqBracket
	KeyCtrl3          KeyCode = termbox.KeyCtrl3
	KeyCtrl4          KeyCode = termbox.KeyCtrl4
	KeyCtrlBackslash  KeyCode = termbox.KeyCtrlBackslash
	KeyCtrl5          KeyCode = termbox.KeyCtrl5
	KeyCtrlRsqBracket KeyCode = termbox.KeyCtrlRsqBracket
	KeyCtrl6          KeyCode = termbox.KeyCtrl6
	KeyCtrl7          KeyCode = termbox.KeyCtrl7
	KeyCtrlSlash      KeyCode = termbox.KeyCtrlSlash
	KeyCtrlUnderscore KeyCode = termbox.KeyCtrlUnderscore
	KeySpace          KeyCode = termbox.KeySpace
	KeyBackspace2     KeyCode = termbox.KeyBackspace2
	KeyCtrl8          KeyCode = termbox.KeyCtrl8
)
