// Code generated by "stringer -type PagingRequestType -output paging_request_type_gen.go"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ToLineAbove-0]
	_ = x[ToScrollPageDown-1]
	_ = x[ToLineBelow-2]
	_ = x[ToScrollPageUp-3]
	_ = x[ToScrollLeft-4]
	_ = x[ToScrollRight-5]
	_ = x[ToLineInPage-6]
	_ = x[ToScrollFirstItem-7]
	_ = x[ToScrollLastItem-8]
}

const _PagingRequestType_name = "ToLineAboveToScrollPageDownToLineBelowToScrollPageUpToScrollLeftToScrollRightToLineInPageToScrollFirstItemToScrollLastItem"

var _PagingRequestType_index = [...]uint8{0, 11, 27, 38, 52, 64, 77, 89, 106, 122}

func (i PagingRequestType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PagingRequestType_index)-1 {
		return "PagingRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PagingRequestType_name[_PagingRequestType_index[idx]:_PagingRequestType_index[idx+1]]
}
