// Code generated by "stringer -type PagingRequestType -output stringer_paging_request_type.go ."; DO NOT EDIT.

package ui

import "fmt"

const _PagingRequestType_name = "ToLineAboveToScrollPageDownToLineBelowToScrollPageUpToScrollLeftToScrollRightToLineInPageToScrollFirstItemToScrollLastItem"

var _PagingRequestType_index = [...]uint8{0, 11, 27, 38, 52, 64, 77, 89, 106, 122}

func (i PagingRequestType) String() string {
	if i < 0 || i >= PagingRequestType(len(_PagingRequestType_index)-1) {
		return fmt.Sprintf("PagingRequestType(%d)", i)
	}
	return _PagingRequestType_name[_PagingRequestType_index[i]:_PagingRequestType_index[i+1]]
}
