// Code generated by "stringer -type VerticalAnchor -output stringer_vertical_anchor.go ."; DO NOT EDIT.

package ui

import "fmt"

const _VerticalAnchor_name = "AnchorTopAnchorBottom"

var _VerticalAnchor_index = [...]uint8{0, 9, 21}

func (i VerticalAnchor) String() string {
	i -= 1
	if i < 0 || i >= VerticalAnchor(len(_VerticalAnchor_index)-1) {
		return fmt.Sprintf("VerticalAnchor(%d)", i+1)
	}
	return _VerticalAnchor_name[_VerticalAnchor_index[i]:_VerticalAnchor_index[i+1]]
}
